args_combination:
  dataset: [
    # "power",
    # "bjaq",
    # "forest",
    # "census",
    # "bjaq_gaussian",
    # "census_gaussian",
    "stats",
  ]
  model_update: [
    # "none",
    "update",
    "adapt",
  ]
  update_size: [
    # 8000, # census
  #  100000, # forest
  #  80000, # bjaq
  #  400000, # power
  # 28000,
  10000,
  ]
  data_update: [
    # "sample",
    "tupleskew",
    # "valueskew"
  ]  # data update
  model: [
    "naru",
    # "face",
    # "transformer",
  ]  # model
  num_workload: [
    # 11,
    3
    # 15,
  ]  
  # query_seed: [6,7] 
  "query_seed": [0]
  "num_queries": [
    100,
    # 1000,
  ]

params_combination:
  data_updater.skew_ratio: [
    # 1e-1,
    1e-2,
    # 1e-3,
    # 1e-4
  ]  # end2end/data_updater.py
  random_seed: [
    # 9,
    # 7,
    # 5,
    # 4,
    # 1,
    0,
  ]  # Naru/eval_model.py
  naru.epochs: [
    # 0,
    # 1,
    20,
  ] 
  face.learning_rate: [
#     5e-06,
    # 5e-05,
#     5e-04,
    1e-4,
#     2e-3,
  ]  
  face.epochs: [
    # 30,
    # 40,
#     50,
    0
  ]  
  face.factor: [
    "auto",
#     "reverse",
#     0.25,
#     0.3,
#     0.5,
#     0.75,
#     1
  ]
  transformer.epochs: [
    0,
    # 40
  ] 
