args_combination:
  dataset: ["forest"]
  model_update: ["none", "update", "adapt"]
  update_size: [25000]
  data_update: ["valueskew"]
  model: ["naru"]
  num_workload: [15]
  query_seed: [0]
  num_queries: [1000]

params_combination:
  data_updater.skew_ratio: [1e-2]
  random_seed: [1]
  naru.epochs: [40]
