args_combination:
  dataset: ["census"]
  model_update: ["none", "update", "adapt"]
  update_size: [4000]
  data_update: ["tupleskew"]
  model: ["transformer"]
  num_workload: [15]
  query_seed: [8]
  num_queries: [1000]

params_combination:
  data_updater.skew_ratio: [1e-2]
  random_seed: [4]
  transformer.epochs: [40]
