args_combination:
  dataset: ["bjaq"]
  model_update: ["none", "update", "adapt"]
  update_size: [20000]
  data_update: ["valueskew"]
  model: ["transformer"]
  num_workload: [15]
  query_seed: [0]
  num_queries: [1000]

params_combination:
  data_updater.skew_ratio: [1e-3]
  random_seed: [0]
  transformer.epochs: [40]
