GPU_ID: 1
dataset_name: "power"

# network parameters
hidden_features: 108
num_flow_steps: 6
flow_id: 1
features: 6
reuse_from_file: false
reuse_file_path: "./FACE/train/"

# query settings
query_seed: 55
query_cnt: 50

# detailed network parameters
anneal_learning_rate: true
base_transform_type: "rq-coupling"
dropout_probability: 0
grad_norm_clip_value: 5.0
linear_transform_type: "lu"
num_bins: 8
num_training_steps: 400000
num_transform_blocks: 2
seed: 1638128
tail_bound: 3
use_batch_norm: false

# update parameters
train_batch_size: 512
learning_rate: 0.0005
monitor_interval: 5000
anneal_learning_rate: True

