INSERT INTO job_light_sub_query_results (count_value) VALUES
((SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_companies mc WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=112 AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=112)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,title t WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=112 AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year>2005 AND t.production_year<2010 AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_companies mc WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=113 AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=113 AND t.production_year>2005 AND t.production_year<2010)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,title t WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=113 AND mc.company_type_id=2 AND t.production_year>2005 AND t.production_year<2010)),
((SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year>2010 AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_companies mc WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=112 AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=112 AND t.production_year>2010)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,title t WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=112 AND mc.company_type_id=2 AND t.production_year>2010)),
((SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year>2000 AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_companies mc WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=113 AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=113 AND t.production_year>2000)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,movie_companies mc,title t WHERE t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=113 AND mc.company_type_id=2 AND t.production_year>2000)),
((SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id)),
((SELECT COUNT(*) FROM title t,movie_keyword mk,movie_companies mc WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND mk.keyword_id=117)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id=117)),
((SELECT COUNT(*) FROM movie_keyword mk,movie_companies mc,title t WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND mk.keyword_id=117)),
((SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.production_year>2005)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.production_year>2005)),
((SELECT COUNT(*) FROM title t,movie_keyword mk,movie_info mi WHERE t.id=mk.movie_id AND t.id=mi.movie_id)),
((SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info mi WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.production_year>2005)),
((SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.production_year>2010)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.production_year>2010)),
((SELECT COUNT(*) FROM title t,movie_keyword mk,movie_info mi WHERE t.id=mk.movie_id AND t.id=mi.movie_id)),
((SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info mi WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.production_year>2010)),
((SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.production_year>1990)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.production_year>1990)),
((SELECT COUNT(*) FROM title t,movie_keyword mk,movie_info mi WHERE t.id=mk.movie_id AND t.id=mi.movie_id)),
((SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info mi WHERE t.id=mk.movie_id AND t.id=mi.movie_id AND t.production_year>1990)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=101 AND t.production_year>2005)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.production_year>2005)),
((SELECT COUNT(*) FROM title t,movie_keyword mk,movie_info_idx mi_idx WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.production_year>2005 AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=101 AND t.production_year>2010)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.production_year>2010)),
((SELECT COUNT(*) FROM title t,movie_keyword mk,movie_info_idx mi_idx WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.production_year>2010 AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=101 AND t.production_year>1990)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.production_year>1990)),
((SELECT COUNT(*) FROM title t,movie_keyword mk,movie_info_idx mi_idx WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM movie_keyword mk,title t,movie_info_idx mi_idx WHERE t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.production_year>1990 AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.production_year>2005)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_type_id=2 AND t.production_year>2005)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_type_id=2 AND t.production_year>2005)),
((SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.production_year>2010)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_type_id=2 AND t.production_year>2010)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_type_id=2 AND t.production_year>2010)),
((SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND t.production_year>1990)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_type_id=2 AND t.production_year>1990)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_type_id=2 AND t.production_year>1990)),
((SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>2010 AND mk.keyword_id=8200)),
((SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=8200)),
((SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND t.production_year>2010)),
((SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=8200 AND t.production_year>2010)),
((SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>2014)),
((SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id)),
((SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND t.production_year>2014)),
((SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.production_year>2014)),
((SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>2014 AND mk.keyword_id=8200)),
((SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=8200)),
((SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND t.production_year>2014)),
((SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=8200 AND t.production_year>2014)),
((SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>2000 AND mk.keyword_id=8200)),
((SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=8200)),
((SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND t.production_year>2000)),
((SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id=8200 AND t.production_year>2000)),
((SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>2000)),
((SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id)),
((SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND t.production_year>2000)),
((SELECT COUNT(*) FROM cast_info ci,movie_keyword mk,title t WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.production_year>2000)),
((SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year>1980 AND t.production_year<1995)),
((SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year>1980 AND t.production_year<1984)),
((SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year>1980 AND t.production_year<2010)),
((SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.role_id=2)),
((SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=2)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id)),
((SELECT COUNT(*) FROM movie_companies mc,cast_info ci,title t WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=2)),
((SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.role_id=4)),
((SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=4)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id)),
((SELECT COUNT(*) FROM movie_companies mc,cast_info ci,title t WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=4)),
((SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.role_id=7)),
((SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=7)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id)),
((SELECT COUNT(*) FROM movie_companies mc,cast_info ci,title t WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=7)),
((SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year>2005 AND t.production_year<2015 AND ci.role_id=2)),
((SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=2)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.production_year>2005 AND t.production_year<2015)),
((SELECT COUNT(*) FROM movie_companies mc,cast_info ci,title t WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=2 AND t.production_year>2005 AND t.production_year<2015)),
((SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year>2007 AND t.production_year<2010 AND ci.role_id=2)),
((SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=2)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.production_year>2007 AND t.production_year<2010)),
((SELECT COUNT(*) FROM movie_companies mc,cast_info ci,title t WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=2 AND t.production_year>2007 AND t.production_year<2010)),
((SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.role_id=1 AND t.production_year>2005)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.production_year>2005)),
((SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=1)),
((SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year>2005 AND ci.role_id=1)),
((SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND ci.role_id=1 AND t.production_year>2010)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.production_year>2010)),
((SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=1)),
((SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year>2010 AND ci.role_id=1)),
((SELECT COUNT(*) FROM cast_info ci,title t WHERE t.id=ci.movie_id AND t.production_year>1990)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.production_year>1990)),
((SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id)),
((SELECT COUNT(*) FROM movie_companies mc,title t,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year>1990)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id=398 AND t.production_year>1950 AND t.production_year<2000)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_type_id=2 AND t.production_year>1950 AND t.production_year<2000)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_type_id=2 AND mk.keyword_id=398)),
((SELECT COUNT(*) FROM movie_companies mc,title t,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_type_id=2 AND t.production_year>1950 AND t.production_year<2000 AND mk.keyword_id=398)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND mk.keyword_id=398)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_type_id=2)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_type_id=2 AND mk.keyword_id=398)),
((SELECT COUNT(*) FROM movie_companies mc,title t,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_type_id=2 AND mk.keyword_id=398)),
((SELECT COUNT(*) FROM movie_keyword mk,title t WHERE t.id=mk.movie_id AND t.production_year>1950)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND t.production_year>1950)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id)),
((SELECT COUNT(*) FROM movie_companies mc,title t,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.production_year>1950)),
((SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=3 AND t.production_year>2005 AND t.production_year<2008)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=101 AND t.production_year>2005 AND t.production_year<2008)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id AND mc.company_type_id=2 AND t.production_year>2005 AND t.production_year<2008)),
((SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_info mi WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND mi_idx.info_type_id=101 AND mi.info_type_id=3)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_type_id=2 AND mi.info_type_id=3)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mc.company_type_id=2 AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t,movie_info mi WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND mi_idx.info_type_id=101 AND t.production_year>2005 AND t.production_year<2008 AND mi.info_type_id=3)),
((SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_type_id=2 AND t.production_year>2005 AND t.production_year<2008 AND mi.info_type_id=3)),
((SELECT COUNT(*) FROM movie_companies mc,title t,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mc.company_type_id=2 AND t.production_year>2005 AND t.production_year<2008 AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mc.company_type_id=2 AND mi.info_type_id=3 AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM movie_companies mc,title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mc.company_type_id=2 AND t.production_year>2005 AND t.production_year<2008 AND mi.info_type_id=3 AND mi_idx.info_type_id=101)),
((SELECT COUNT(*) FROM movie_info mi,title t WHERE t.id=mi.movie_id AND mi.info_type_id=105)),
((SELECT COUNT(*) FROM movie_info_idx mi_idx,title t WHERE t.id=mi_idx.movie_id AND mi_idx.info_type_id=113)),
((SELECT COUNT(*) FROM movie_companies mc,title t WHERE t.id=mc.movie_id)),
((SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_info mi WHERE t.id=mi_idx.movie_id AND t.id=mi.movie_id AND mi_idx.info_type_id=113 AND mi.info_type_id=105)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mi.info_type_id=105)),
((SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=113));
